version: '3.8'

services:
  web:
    build: .
    container_name: template_flask_web
    image: template_flask
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: template_flask_db
    restart: always
    environment:
      MYSQL_DATABASE: template_db
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}